# Generated by Django 5.1.4 on 2025-01-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
